name = "cqil-health-router"
type = "javascript"
compatibility_date = "2023-05-18"

[env.production]
zone_id = "27e4e83fb4c91289b3d620ebc2c917e9"
routes = [
  "cqil.ca/*"
]

[env.staging]
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes